# Generated by Django 3.1.4 on 2021-01-02 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vkbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование специальности')),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='vk_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='Вк_Id'),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Номер группы')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vkbot.specialization')),
            ],
        ),
    ]
