# Generated by Django 3.1.4 on 2021-01-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkbot', '0004_auto_20210104_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Фамилия Имя'),
        ),
    ]
