# Generated by Django 3.1.4 on 2021-01-04 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vkbot', '0005_auto_20210104_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='specialnost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vkbot.specialization', verbose_name='специальность'),
        ),
    ]
