# Generated by Django 3.1.4 on 2021-02-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkbot', '0007_auto_20210105_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='send_date',
            field=models.CharField(max_length=255, null=True, verbose_name='Дата отправки'),
        ),
        migrations.AddField(
            model_name='users',
            name='send_message',
            field=models.TextField(null=True, verbose_name='Отправленное сообщение'),
        ),
    ]
