# Generated by Django 3.1.4 on 2021-02-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkbot', '0008_auto_20210205_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_id', models.CharField(max_length=255, unique=True, verbose_name='Вк_Id')),
            ],
        ),
    ]
